# Generated by Django 3.2.2 on 2021-12-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.CharField(max_length=100)),
                ('cert_name', models.CharField(max_length=100)),
                ('synop', models.CharField(max_length=100)),
                ('cert_year', models.CharField(max_length=4)),
                ('cert_month', models.CharField(max_length=10)),
                ('desc', models.TextField()),
                ('test_score', models.CharField(max_length=100)),
            ],
        ),
    ]
